preferencia1(professor1, matematica_discreta).
preferencia1(professor2, algoritmos_e_programacao).
preferencia1(professor2, arquitetura_e_organizacao_pc).
preferencia1(professor3, linguagens_formais).
preferencia1(professor3, logica_matematica).
preferencia1(professor3, matematica_discreta).
preferencia1(professor4, algoritmos_e_programacao).
preferencia1(professor4, arquitetura_e_organizacao_pc).
preferencia1(professor4, estrutura_de_dados).
preferencia1(professor5, algoritmos_e_programacao).
preferencia1(professor6, resolucao_de_problemas_iii).
preferencia1(professor7, algoritmos_e_programacao).
preferencia1(professor7, arquitetura_e_organizacao_pc).
preferencia1(professor8, algoritmos_e_programacao).
preferencia1(professor8, arquitetura_e_organizacao_pc).
preferencia1(professor8, estrutura_de_dados).
preferencia1(professor8, logica_matematica).
preferencia1(professor9, inovacao_e_criatividade).
preferencia1(professor11, resolucao_de_problemas_i).
preferencia1(professor12, analise_e_projeto_de_software).
preferencia1(professor12, algoritmos_e_programacao).
preferencia1(professor13, analise_e_projeto_de_software).
preferencia1(professor13, resolucao_de_problemas_i).
preferencia1(professor14, algoritmos_e_programacao).
preferencia1(professor14, estrutura_de_dados).
preferencia1(professor15, analise_e_projeto_de_software).
preferencia1(professor15, resolucao_de_problemas_i).
preferencia1(professor15, resolucao_de_problemas_iii).
preferencia1(professor16, linguagens_formais).
preferencia1(professor16, logica_matematica).
preferencia1(professor16, matematica_discreta).
preferencia1(professor17, resolucao_de_problemas_i).
preferencia1(professor18, algoritmos_e_programacao).
preferencia1(professor18, estrutura_de_dados).
preferencia1(professor19, algoritmos_e_programacao).
preferencia1(professor19, estrutura_de_dados).
preferencia1(professor19, estrutura_de_dados).
preferencia1(professor20, resolucao_de_problemas_i).
preferencia1(professor20, algoritmos_e_programacao).
preferencia1(professor21, algoritmos_e_programacao).
preferencia1(professor22, resolucao_de_problemas_i).




preferencia3(professor10, inovacao_e_criatividade).
preferencia3(professor12, inovacao_e_criatividade).
preferencia3(professor5, analise_e_projeto_de_software).
preferencia3(professor6, analise_e_projeto_de_software).
preferencia3(professor7, analise_e_projeto_de_software).
preferencia3(professor11, analise_e_projeto_de_software).
preferencia3(professor12, inovacao_e_criatividade).
preferencia3(professor2, resolucao_de_problemas_i).
preferencia3(professor9, resolucao_de_problemas_i).
preferencia3(professor12, resolucao_de_problemas_iii).
preferencia3(professor17, resolucao_de_problemas_iii).
preferencia3(professor21, arquitetura_e_organizacao_pc).
preferencia3(professor5, estruturas_de_dados).
preferencia3(professor6, estruturas_de_dados).
preferencia3(professor10, estruturas_de_dados).
preferencia3(professor13, estruturas_de_dados).
preferencia3(professor15, estruturas_de_dados).
preferencia3(professor20, estruturas_de_dados).
preferencia3(professor19, logica_matematica).